name: TabooMenu
main: me.skymc.taboomenu.TabooMenu

api-version: 1.13
version: 2.61

author: [filoghost, 坏黑]
softdepend: [Vault, PlayerPoints, PlaceholderAPI, TabooLib, TabooScript]

commands:
  taboomenu:
    aliases: [tmenu, tm, cc]
